[package]
name = "github_sum_embed_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
llmchain = "0.1.3"
tokio = { version = "1.0", features = ["full"] }
octocrab = "0.30.1"
anyhow = "1.0"
dotenv = "0.15"
async-openai = "0.10"
parking_lot = "0.12"

